feat: prevent closing the active view when clicking on a disabled hour/minute
kuhnroyal/mat-datetimepicker pull request #353
Opened 2022-08-08 11:51 UTC by Waseem-Isaac

A click on a disabled item should do nothing.
these changes fixes an issue with me, And I think it will fix https://github.com/kuhnroyal/mat-datetimepicker/issues/158 as well.

2022-08-11 03:17 UTC, bbortt requested changes
thx very much! I think this is rather a fix, than a feature, right? so I'd type the commit as `fix(#158):`.
and since you will have to amend the commit, I also left two small lints I'd correct.

2022-08-11 03:17 UTC, bbortt commented on projects/core/src/datetimepicker/clock.ts
> +      }
I'd add a newline here ;)

2022-08-11 03:17 UTC, bbortt commented on projects/core/src/datetimepicker/clock.ts
> +      }
and here as well.

2022-08-11 12:07 UTC, Waseem-Isaac commented
> thx very much! I think this is rather a fix, than a feature, right? so I'd type the commit as `fix(#158):`. and since you will have to amend the commit, I also left two small lints I'd correct.

I agree, Honestly I noticed  #158 after I added my fix :), I made it for another issue appeared with me.

2022-08-20 21:09 UTC, bbortt approved these changes
thank you :)

2022-08-20 21:11 UTC, merged