feat: angular 15 release
kuhnroyal/mat-datetimepicker pull request #404
Opened 2022-11-24 17:01 UTC by gsontag

BREAKING CHANGES: upgrade to `@angular/core 15.0.x` is required!

2022-11-24 21:49 UTC, bbortt requested changes

2022-11-24 21:49 UTC, bbortt commented on projects/moment/package.json
>      "@mat-datetimepicker/core": "^10.0.0"
I think this bump will not happen automatically!

```suggestion
    "@mat-datetimepicker/core": "^11.0.0"
```

2022-11-24 21:49 UTC, bbortt commented on src/styles.scss
> +//@import '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';
sorry, I know this is definitely something I should do, but I do not find any time. would you mind updating the [theming part of the `README.md`](https://github.com/kuhnroyal/mat-datetimepicker#theming) as well?

2022-11-24 21:49 UTC, bbortt commented
closes #403.

2022-11-25 14:28 UTC, gsontag commented
Made a workaround in angular.json for empty test suite because "failOnEmptyTestSuite: false" seems to be ignored

2022-11-29 09:37 UTC, bbortt requested changes
sorry, I might have confused you with my previous comments..

2022-11-29 09:37 UTC, bbortt commented on projects/moment/package.json
> +  "version": "11.0.0",
sorry if I confused you with [my earlier comment](https://github.com/kuhnroyal/mat-datetimepicker/pull/404#discussion_r1031869570). this version will be bumped (see the [`.releaserc.js`](https://github.com/kuhnroyal/mat-datetimepicker/blob/release/.releaserc.js#L35) configuration)! just not the `peerDependencies`. please revert just this line.

2022-11-29 09:37 UTC, bbortt commented on projects/core/package.json
> +  "version": "11.0.0",
this version will be bumped (see the [`.releaserc.js`](https://github.com/kuhnroyal/mat-datetimepicker/blob/release/.releaserc.js#L35) configuration)! please revert this change.

2022-11-29 11:06 UTC, gsontag commented on projects/core/package.json
> +  "version": "11.0.0",
ah, ok :p not used to releaserc

2022-11-29 16:53 UTC, bbortt approved these changes
thanks so much, I've checked it out too and everything looks fine to me. let's ship this 🚀

2022-11-29 16:54 UTC, merged